// Generated by CoffeeScript 1.6.3
(function() {
  var $name, Profile, ProfilesCollection, createDefaultProfile, debouncedSave, logDebug, profiles, profilesFetch, saveText, theProfile;

  logDebug = true;

  $name = $("#name");

  Profile = Backbone.Model.extend({
    defaults: {
      name: 'Full Name',
      tagline: 'A short description of what I do.'
    }
  });

  ProfilesCollection = Backbone.Collection.extend({
    model: Profile,
    localStorage: new Store('profiles')
  });

  profiles = new ProfilesCollection();

  theProfile = null;

  createDefaultProfile = function() {
    if (logDebug) {
      console.log("len", profiles.length);
    }
    if (profiles.length > 0) {
      if (logDebug) {
        console.log("found profile");
      }
      theProfile = profiles.at(0);
      return $name.html(theProfile.get("name"));
    } else {
      if (logDebug) {
        console.log("create profile");
      }
      return theProfile = profiles.create({
        copy: $name.html()
      });
    }
  };

  saveText = function() {
    console.log("save text", $name.html());
    theProfile.set("name", $name.html());
    return theProfile.save();
  };

  debouncedSave = _.debounce(saveText, 100);

  $name.keyup(debouncedSave);

  profilesFetch = profiles.fetch();

  profilesFetch.done(createDefaultProfile);

}).call(this);
